"""Changed splitbill model

Revision ID: 06a210062009
Revises: e444c69205c9
Create Date: 2025-09-23 17:30:40.572765

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "06a210062009"
down_revision: Union[str, Sequence[str], None] = "e444c69205c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "balances", ["id"])
    op.create_unique_constraint(None, "comments", ["id"])
    op.create_unique_constraint(None, "expenseassignments", ["id"])
    op.create_unique_constraint(None, "expenses", ["id"])
    op.create_unique_constraint(None, "moneygiven", ["id"])
    op.create_unique_constraint(None, "pendingusers", ["id"])
    op.create_unique_constraint(None, "splitbillmembers", ["id"])
    op.alter_column(
        "splitbills", "currency", existing_type=sa.VARCHAR(length=10), nullable=True
    )
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "splitbills", "currency", existing_type=sa.VARCHAR(length=10), nullable=False
    )
    op.drop_constraint(None, "splitbillmembers", type_="unique")
    op.drop_constraint(None, "pendingusers", type_="unique")
    op.drop_constraint(None, "moneygiven", type_="unique")
    op.drop_constraint(None, "expenses", type_="unique")
    op.drop_constraint(None, "expenseassignments", type_="unique")
    op.drop_constraint(None, "comments", type_="unique")
    op.drop_constraint(None, "balances", type_="unique")
    # ### end Alembic commands ###
