"""Upgrading models

Revision ID: 07ad6262e839
Revises: 7f177e455b3f
Create Date: 2025-09-27 17:40:08.524172

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "07ad6262e839"
down_revision: Union[str, Sequence[str], None] = "7f177e455b3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
