"""Updating models

Revision ID: 256cf6b1c829
Revises: 49de81064af5
Create Date: 2025-09-24 12:10:46.600524

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "256cf6b1c829"
down_revision: Union[str, Sequence[str], None] = "49de81064af5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "balances",
        sa.Column(
            "status",
            sa.Enum("active", "settled", name="splitbillstatusenum", native_enum=False),
            nullable=False,
        ),
    )
    op.drop_column("balances", "active")
    op.create_unique_constraint(
        "uq_splitbill_alias", "splitbillmembers", ["splitbill_id", "alias"]
    )
    op.add_column(
        "users", sa.Column("hashed_password", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "users",
        sa.Column(
            "date_updated",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_column("users", "updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("users", "date_updated")
    op.drop_column("users", "hashed_password")
    op.drop_constraint("uq_splitbill_alias", "splitbillmembers", type_="unique")
    op.add_column(
        "balances",
        sa.Column("active", sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    )
    op.drop_column("balances", "status")
    # ### end Alembic commands ###
