"""Updating models

Revision ID: 3287f218545d
Revises: 6ee6ad3214aa
Create Date: 2025-09-24 11:07:23.585269

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3287f218545d"
down_revision: Union[str, Sequence[str], None] = "6ee6ad3214aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("pendingusers", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "pendingusers", "alias", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pendingusers", "alias", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column("pendingusers", "email", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
