"""Guest model

Revision ID: 3e9560b8a3e9
Revises: 07ad6262e839
Create Date: 2025-10-06 15:36:15.904100

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e9560b8a3e9"
down_revision: Union[str, Sequence[str], None] = "07ad6262e839"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guest",
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("splitbill_id", sa.Integer(), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expires", sa.DateTime(), nullable=True),
        sa.Column("used_by_user", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["splitbill_id"],
            ["splitbills.id"],
        ),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_index(op.f("ix_guest_token"), "guest", ["token"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_guest_token"), table_name="guest")
    op.drop_table("guest")
    # ### end Alembic commands ###
