"""Updating models

Revision ID: 49de81064af5
Revises: 3287f218545d
Create Date: 2025-09-24 12:00:11.322946

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "49de81064af5"
down_revision: Union[str, Sequence[str], None] = "3287f218545d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
