"""Updating models

Revision ID: 62ac50eeba05
Revises: 256cf6b1c829
Create Date: 2025-09-24 12:25:03.767539

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "62ac50eeba05"
down_revision: Union[str, Sequence[str], None] = "256cf6b1c829"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
