"""Updating models

Revision ID: 65a93132c3ab
Revises: 62ac50eeba05
Create Date: 2025-09-24 15:21:28.227144

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "65a93132c3ab"
down_revision: Union[str, Sequence[str], None] = "62ac50eeba05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
