"""Upgrading models

Revision ID: 7f177e455b3f
Revises: 949bd74555ef
Create Date: 2025-09-27 16:53:17.063682

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "7f177e455b3f"
down_revision: Union[str, Sequence[str], None] = "949bd74555ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
