"""Added activation_token to UsersOrm

Revision ID: 8132ac7683e2
Revises: df3d8456e3f2
Create Date: 2025-09-26 21:19:55.756618

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8132ac7683e2"
down_revision: Union[str, Sequence[str], None] = "df3d8456e3f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("activation_token", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "activation_token")
    # ### end Alembic commands ###
