"""Updating models

Revision ID: c68c06239e08
Revises: 06a210062009
Create Date: 2025-09-23 17:46:29.618301

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "c68c06239e08"
down_revision: Union[str, Sequence[str], None] = "06a210062009"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
