"""Updating models

Revision ID: db9bce7268a3
Revises: 804ca5e5e950
Create Date: 2025-09-23 18:51:41.553006

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "db9bce7268a3"
down_revision: Union[str, Sequence[str], None] = "804ca5e5e950"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "is_active",
        existing_type=postgresql.ENUM("active", "pending", name="userstatusorm"),
        type_=sa.Enum("active", "pending", name="userstatusorm", native_enum=False),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "is_active",
        existing_type=sa.Enum(
            "active", "pending", name="userstatusorm", native_enum=False
        ),
        type_=postgresql.ENUM("active", "pending", name="userstatusorm"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
