"""Models update

Revision ID: df3d8456e3f2
Revises: ed5908438846
Create Date: 2025-09-26 19:57:39.081591

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "df3d8456e3f2"
down_revision: Union[str, Sequence[str], None] = "ed5908438846"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("splitbills_owner_id_fkey"), "splitbills", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "splitbills", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "splitbills", type_="foreignkey")
    op.create_foreign_key(
        op.f("splitbills_owner_id_fkey"),
        "splitbills",
        "splitbillmembers",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
