"""Updating models

Revision ID: dff12f9ddc14
Revises: 65a93132c3ab
Create Date: 2025-09-26 18:28:05.025633

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "dff12f9ddc14"
down_revision: Union[str, Sequence[str], None] = "65a93132c3ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("pendingusers_email_key"), "pendingusers", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("pendingusers_email_key"),
        "pendingusers",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
