"""Models update

Revision ID: ed5908438846
Revises: dff12f9ddc14
Create Date: 2025-09-26 19:54:13.012009

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ed5908438846"
down_revision: Union[str, Sequence[str], None] = "dff12f9ddc14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("splitbills_owner_id_fkey"), "splitbills", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "splitbills", "splitbillmembers", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "splitbills", type_="foreignkey")
    op.create_foreign_key(
        op.f("splitbills_owner_id_fkey"),
        "splitbills",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
